#!/usr/bin/env bash
# installs and configures HAProxy in my lb01 server

sudo apt-get update
sudo apt-get install -y haproxy

echo "ENABLED=1" >> /etc/default/haproxy

echo "
    listen load_balancer
    bind *:80
    mode http
    balance roundrobin
    option httpclose
    option forwardfor
    server 15692-web-01 34.232.64.104 check
    server 15692-web-02 3.236.211.190 check
    option httpchk
" >> /etc/haproxy/haproxy.cfg
sudo service haproxy start
